// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmrxwbungwpdlhdyxcdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtcnh3YnVuZ3dwZGxoZHl4Y2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQyOTc2NzQsImV4cCI6MjA5OTg3MzY3NH0.Tx9vdS2__DDCNTwzIZpswCA7QBYGJypKl_gaHxyEP0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});